// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSUIAUBZhTpXK_R67aQ9o2zPXPLNGNN2o',
    appId: '1:766196147833:web:3782ea66ae837c396616a8',
    messagingSenderId: '766196147833',
    projectId: 'chatting-b318c',
    authDomain: 'chatting-b318c.firebaseapp.com',
    storageBucket: 'chatting-b318c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF2DZZGPey4QyFXX6VhhQjuKrkZeeApfM',
    appId: '1:766196147833:android:f0e8dd4ab8017bc46616a8',
    messagingSenderId: '766196147833',
    projectId: 'chatting-b318c',
    storageBucket: 'chatting-b318c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGLyXBp3zE5e5KHoIjpM9NpcVoW75CyHk',
    appId: '1:766196147833:ios:2951d8780ad8fedb6616a8',
    messagingSenderId: '766196147833',
    projectId: 'chatting-b318c',
    storageBucket: 'chatting-b318c.firebasestorage.app',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGLyXBp3zE5e5KHoIjpM9NpcVoW75CyHk',
    appId: '1:766196147833:ios:2951d8780ad8fedb6616a8',
    messagingSenderId: '766196147833',
    projectId: 'chatting-b318c',
    storageBucket: 'chatting-b318c.firebasestorage.app',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSUIAUBZhTpXK_R67aQ9o2zPXPLNGNN2o',
    appId: '1:766196147833:web:c727fbfac4a0e50b6616a8',
    messagingSenderId: '766196147833',
    projectId: 'chatting-b318c',
    authDomain: 'chatting-b318c.firebaseapp.com',
    storageBucket: 'chatting-b318c.firebasestorage.app',
  );
}
